- hosts: role_master
  tasks:
      
  - name: deploy petclinic application
    shell: |
      kubectl delete secret regcred -n petclinic-staging-ns || true
      kubectl create secret generic regcred -n petclinic-staging-ns \
        --from-file=.dockerconfigjson=$JENKINS_HOME/.docker/config.json \
        --type=kubernetes.io/dockerconfigjson
      kubectl apply -k k8s/dev/